name: Deploy Backend

on:
  push:
    branches:
      - main

  workflow_dispatch:

    jobs:
      deploy:
        runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        working-directory: ./backend
        run: docker build -t wishy-backend:latest .

      - name: Save Docker image to .tar
        working-directory: ./backend
        run: docker save wishy-backend:latest -o wishy-backend.tar

      - name: Copy image .tar to the server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}         
          username: ${{ secrets.SERVER_USER }}     
          password: ${{ secrets.SERVER_USER_PASSWORD }}  
          source: "./backend/wishy-backend.tar"                         
          target: "/home/${{ secrets.SERVER_USER }}/server" 


